apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    uid: prometheus_ds
    isDefault: true
    editable: true
    
  - name: InstagramLoki
    type: loki
    access: proxy
    url: http://loki:3100
    uid: instagram_loki
    isDefault: false
    editable: true

  - name: Redis
    type: redis-datasource
    access: proxy
    url: redis://redis:6379
    uid: redis_ds
    editable: true
