{
 "title": "Observabilidade - Instagram",
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "endpoint",
    "query": "label_values(http_server_requests_seconds_count, uri)"
   }
  ]
 },
 "panels": [
  {
   "title": "Usuários Logados Atualmente",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "targets": [
    { "expr": "instagram_active_sessions", "legendFormat": "Ativos" }
   ]
  },
  {
   "title": "Taxa de Requisições HTTP Backend",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count{uri=~\"$endpoint\"}[15s])",
     "legendFormat": "{{uri}} - {{status}}"
    }
   ]
  },
  {
   "title": "Usuários Online e Seus IPs",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "instagram_user_active_sessions == 1"
    }
   ]
  },
  {
   "title": "Logs de Mensagens (Tráfego de Rede / Payloads)",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "{app=\"instagram\"} |= \"PAYLOAD:\" |~ \"$endpoint\""
    }
   ]
  },
  {
   "title": "Tokens na Blacklist",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
   "targets": [
    { "query": "KEYS token_blacklist:*", "command": "cli" }
   ]
  }
 ]
}