spring.application.name=instagram

# Banco de dados
spring.datasource.url=jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5432}/${DATABASE_NAME:instagram}
spring.datasource.username=${DATABASE_USER:postgres}
spring.datasource.password=${DATABASE_PASSWORD:1234}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none

# Flyway - Migrations
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true

# Swagger UI Multiple OpenAPI configurations
springdoc.swagger-ui.urls[0].name=API Instagram (Nova)
springdoc.swagger-ui.urls[0].url=/v3/api-docs

springdoc.swagger-ui.urls[1].name=API (Gerenciamento de Usuarios - Pronta)
springdoc.swagger-ui.urls[1].url=/allvesleooorganizati-instagram-api-gerenciamento-de-usuarios-1.0.1-resolved.json

# Segurança JWT Customizada
api.security.token.secret=${JWT_SECRET:segredo-do-jwt-do-instagram-2026}

# Redis (Token Revocation Cache Tracker)
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}